# Generated by Django 4.0.5 on 2022-06-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_remove_image_comments_remove_image_likes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_caption',
            field=models.CharField(max_length=100),
        ),
    ]
