# Generated by Django 4.0.5 on 2022-06-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0006_remove_likes_image_likes_date_alter_likes_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
